name: test

on:
  pull_request:
    # branches:
    # - "*"
  workflow_dispatch:
#   schedule:
#   - cron: '0 0 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
    - name: create json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "credentials.json"
        json: ${{ secrets.CREDENTIALS }}
        dir: 'fixtures/'       
    - name: run npm ci
      run: npm ci
    - name: install dependencies
      run: npm install
    - name: install playwright
      run: npx playwright install-deps
    - name: run playwright test
      run: xvfb-run --auto-servernum -- npm test
    - name: upload report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
    - name: show directory
      if: always()
      run: pwd & ls
    - name: deploy to github pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: playwright-report
