name: test

on:
  pull_request:
    branches: master
  workflow_dispatch:
#   schedule:
#   - cron: '0 0 * * *'

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v6
    # - name: create json
    #   uses: jsdaniell/create-json@v1.2.2
    #   with:
    #     name: "credentials.json"
    #     json: ${{ secrets.CREDENTIALS }}
    #     dir: 'fixtures/'       
    - name: install depencencies
      run: npm ci
    - name: install playwright dependencies
      run: npx playwright install --with-deps
    - name: run playwright test
      run: xvfb-run --auto-servernum -- npm test
      env:
        SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - name: upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 1
    # - name: show directory
    #   if: always()
    #   run: pwd & ls
    - name: deploy to github pages
      if: github.actor != 'dependabot[bot]'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: playwright-report
